version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis
  redis:
    image: redis
  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - app
      - redis
